[tool.poetry]
name = "feature-engineering-service"
version = "0.1.0"
description = "Feature Engineering Microservice"
authors = ["Tradebotnan Engineering"]
package-mode = false   # <<=== ADD THIS LINE

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2"
numpy = "^1.26"
pyarrow = "^14.0.1"
TA-Lib = "^0.6.3"
python-dotenv = "^1.0.1"

[tool.poetry.scripts]
feature-engineering = "app.main:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
coverage = "^7.8.0"
pytest-cov = "^6.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
