features:
  enabled: true
  version: v1.0
  asset_class: crypto

  price_indicators:
    # Trend
    sma: { periods: [5, 10, 20, 50, 100, 200] }
    ema: { periods: [10, 20, 50, 100] }
    macd: { enabled: true }
    trix: { periods: [15] }
    vortex: { periods: [14] }
    donchian_channel: { periods: [20] }

    # Momentum
    rsi: { periods: [14] }
    roc: { periods: [10] }
    stochastic: { periods: [14] }

    # Volatility
    atr: { periods: [14] }
    bollinger: { periods: [20], stddev: 2 }
    volatility_burst: { zscore_window: 20 }

  volume_indicators:
    obv: { enabled: true }
    mfi: { periods: [14] }
    volume_ema: { periods: [10] }
    volume_roc: { periods: [10] }
    anomalies: { enabled: true }
    vwap: { enabled: true }
    price_vwap_ratio: { enabled: true }

  sentiment_analysis:
    enabled: true
    source: ["social"]
    models: ["vader"]
    sentiment_change: { enabled: true, window: 5 }

  candle_features:
    engineered: { include: ["body_size", "gap_up", "gap_down"] }

  engineered_features:
    return:
      include: ["return_1d", "return_5d", "log_return"]
    volatility:
      windows: [5, 10, 21]
    trend_strength:
      periods: [10, 20]
    zscore:
      apply_to: ["close", "rsi_14"]

  labels:
    trend: { horizon: 1 }
    return_bin: { bins: [-1.0, 0.0, 0.5, 1.0] }
    future_return: { horizon: 1 }
