features:
  enabled: true
  version: v2.0
  asset_class: futures

  momentum_indicators:
    rsi: { periods: [14] }
    roc: { periods: [10] }
    adx: { periods: [14] }
    cci: { periods: [14] }

  trend_indicators:
    sma: { periods: [5, 10, 20, 50, 100, 200] }
    ema: { periods: [10, 20, 50, 100] }
    macd: { enabled: true }
    trix: { periods: [15] }
    vortex: { periods: [14] }

  volatility_indicators:
    atr: { periods: [14] }
    bollinger: { periods: [20], stddev: 2 }

  candle_features:
    engineered.py:
      include: ["gap_up", "body_size"]

  sentiment_analysis:
    enabled: false

  engineered_features:
    return:
      include: ["return_1d", "log_return"]
    volatility:
      windows: [5, 10]
    trend_strength:
      periods: [10, 20]

  labels:
    trend: { horizon: 1 }
    volatility_regime: { thresholds: [0.01, 0.03] }

  trades:
    indicators:
      enabled: false
