features:
  enabled: true
  version: v1.0
  asset_class: stocks

  price_indicators:
    # Trend
    sma: { periods: [5, 10, 20, 50, 100, 200, 250] }
    ema: { periods: [10, 20, 50, 100, 200] }
    wma: { periods: [20] }
    macd: { enabled: true }
    trix: { periods: [15] }
    vortex: { periods: [14] }
    donchian_channel: { periods: [20] }
    ichimoku: { enabled: true }

    # Momentum
    rsi: { periods: [14] }
    roc: { periods: [10] }
    adx: { periods: [14] }
    cci: { periods: [14] }
    stochastic: { periods: [14] }

    # Volatility
    atr: { periods: [14] }
    bollinger: { periods: [20], stddev: 2 }
    true_range_pct: { periods: [14] }

  volume_indicators:
    obv: { enabled: true }
    mfi: { periods: [14] }
    accumulation_distribution: { enabled: true }
    chaikin_money_flow: { periods: [20] }
    volume_roc: { periods: [10] }
    vwap: { enabled: true }
    price_vwap_ratio: { enabled: true }

  fundamentals:
    include: ["pe_ratio", "eps", "dividend_yield", "revenue_growth"]

  sentiment_analysis:
    enabled: true
    source: ["news"]
    models: ["finbert"]

  event_flags:
    enabled: true
    types: ["earnings", "dividend", "splits"]

  candle_features:
    patterns: { enabled: true }
    include: ["doji", "engulfing"]
    engineered: { include: ["body_size", "wick_size", "gap_up", "gap_down"] }

  engineered_features:
    return:
      include: ["return_1d", "return_5d", "log_return"]
    volatility:
      windows: [5, 10, 21]
    trend_strength:
      periods: [10, 20]
    zscore:
      apply_to: ["close", "rsi_14"]
    crosses:
      include: ["ema_10_vs_ema_50", "sma_20_vs_sma_50"]
    sequence_id:
      enabled: true

  labels:
    trend: { horizon: 1 }
    return_bin: { bins: [-1.0, 0.0, 0.5, 1.0] }
    future_return: { horizon: 1 }
